spring:
  jpa:
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

logging:
  level:
    com.creatorx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG_LEVEL:WARN}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BIND_LOG_LEVEL:WARN}



