export const PLATFORM_SETTING_KEYS = {
  FEES_PLATFORM_COMMISSION_PERCENT: 'FEES_PLATFORM_COMMISSION_PERCENT',
  PAYOUT_ALLOWED_DAYS: 'PAYOUT_ALLOWED_DAYS',
  PAYOUT_START_HOUR: 'PAYOUT_START_HOUR',
  PAYOUT_END_HOUR: 'PAYOUT_END_HOUR',
  CATEGORIES_ALLOWED_LIST: 'CATEGORIES_ALLOWED_LIST',
  FEATURE_CAMPAIGN_PREAPPROVAL: 'FEATURE_CAMPAIGN_PREAPPROVAL',
  FEATURE_WITHDRAWALS_ENABLED: 'FEATURE_WITHDRAWALS_ENABLED',
  FEATURE_CATEGORY_ENFORCEMENT: 'FEATURE_CATEGORY_ENFORCEMENT',
} as const

export const WEEKDAY_OPTIONS = [
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY',
  'SUNDAY',
]
